kiss: Do not pass `ensure_future` result to `call_soon`.
`ensure_future` returns an `asyncio.Task`, which does not implement the
"callable" interface and will intermittently trigger the following
error:

```
ERROR    asyncio:base_events.py:1744 Exception in callback <Task pending name='Task-18' coro=<SerialKISSDevice._open_connection() running at /home/stuartl/projects/wicen/aioax25/aioax25/kiss.py:475> wait_for=<Future pending cb=[Task.task_wakeup()]>>()
handle: <Handle <Task pending name='Task-18' coro=<SerialKISSDevice._open_connection() running at /home/stuartl/projects/wicen/aioax25/aioax25/kiss.py:475> wait_for=<Future pending cb=[Task.task_wakeup()]>>()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
TypeError: '_asyncio.Task' object is not callable
```

I say "intermittently", I've never seen it on Github actions logs or on
my own laptop (Core i5 3320M) which runs various Python releases atop
Gentoo Linux/AMD64.  My much older Apple MacBook (Core2 Duo) running
MacOS X 10.6 and Python 3.6.4 does reproduce the problem reliably.

The above traceback happened on Ubuntu 22.04 and Python 3.10.4 on a AMD
Ryzen 7 1700.

In any case, the thing is `ensure_future` effectively _does_ background
the coroutine by wrapping it up in a `Task`, and so there's no need to
pass this back to `IOLoop.call_soon` as this is implicit.  The correct
thing to do it seems is drop it completely.